version: '2.0'
services:
  next:
    build:
      dockerfile: ${PWD}/frontend/.Dockerfile
    restart: always
    ports:
      - 3000:3000
  lightspeech_static_volume:
    build:
      dockerfile: ${PWD}/nginx.Dockerfile
    volumes:
      - ~/LightSpeech/output:/app/static
    restart: always
    ports:
      - 80:80
      - 8080:8080
